// Catálogo inicial de aluviones (flujos de detritos o de barro) en Chile,
// ordenado de norte a sur.
//
// CÓMO SE ARMÓ (octubre de 2026): con resultados de búsqueda web. Desde el
// entorno de trabajo no se pudo abrir ninguna página, así que NINGÚN evento
// está marcado `verificado: true`. Cada uno trae la fuente que lo respalda y
// `confirmacion` según cuánto coincidieron las fuentes en la búsqueda:
//   alta  = fecha y lugar coinciden en 2+ fuentes independientes, al menos
//           una oficial o académica
//   media = una sola fuente, o solo fuentes secundarias que coinciden
//   baja  = hay contradicciones o faltan datos clave
// Abre `fuente_url` y cambia `verificado` a true solo cuando la página
// confirme fecha y lugar.
//
// Coordenadas: centro aproximado de la localidad (ver `coord_nota`). `null`
// = no se encontró una fuente; se ubican con el botón "📍 Ubicar" de la app.
// `fallecidos`: solo cuando una fuente da la cifra; las discrepancias van en
// `fallecidos_nota`.

(function (global) {
  const ALUVIONES = [
    {
      id: "camina-2012", fecha: "2012-03-13", localidad: "Camiña (quebradas de Camiña y Tarapacá)", comuna: "Camiña", region: "Tarapacá",
      lat: -19.313, lon: -69.426, coord_nota: "Ficha de Wikipedia de Camiña",
      desencadenante: "Lluvia intensa de la temporada altiplánica; período de retorno > 100 años según Sepúlveda et al. (2014)",
      fallecidos: null, fallecidos_nota: "Ninguna fuente encontrada da cifra",
      descripcion: "Flujos de detritos y barro dañaron y destruyeron varios pueblos de los valles de Camiña y Tarapacá (Camiña, Chapiquilta, Yala Yala y parte de Cuisama, según el alcalde).",
      fuente_titulo: "Sepúlveda et al. (2014), Landslides 11(3):481-491", fuente_url: "https://repositorio.uchile.cl/handle/2250/126605", tipo_fuente: "académica",
      fuentes_adicionales: ["https://www.redalyc.org/pdf/3713/371333937003.pdf"],
      verificado: false, confirmacion: "alta", nota_verificacion: "Sepúlveda et al. dan solo «marzo 2012»; el día 13 viene de un estudio morfométrico (Redalyc).",
    },
    {
      id: "huatacondo-2025", fecha: "2025-06-26", localidad: "Huatacondo", comuna: "Pozo Almonte", region: "Tarapacá",
      lat: -20.928, lon: -69.055, coord_nota: "World Historical Gazetteer (punto aproximado)",
      desencadenante: "Lluvia de sistema frontal sobre terreno árido; activación y desborde de una quebrada",
      fallecidos: null, fallecidos_nota: "No se informan fallecidos en las fuentes encontradas",
      descripcion: "En la madrugada del 25 al 26 de junio un aluvión de barro y piedras cubrió casi todo el pueblo; decenas de casas quedaron inhabitables.",
      fuente_titulo: "El Dínamo (26-06-2025)", fuente_url: "https://www.eldinamo.cl/pais/2025/06/26/fotos-video-asi-quedo-huatacondo-la-localidad-nortina-arrasada-por-un-aluvion/", tipo_fuente: "secundaria",
      fuentes_adicionales: ["https://eldesconcierto.cl/2025/06/26/video-huatacondo-en-la-region-de-tarapaca-amanece-bajo-el-barro-tras-destructivo-aluvion-durante-la-madrugada"],
      verificado: false, confirmacion: "media", nota_verificacion: "Sin informe oficial de SENAPRED ni SERNAGEOMIN encontrado.",
    },
    {
      id: "tocopilla-2015", fecha: "2015-08-09", localidad: "Tocopilla", comuna: "Tocopilla", region: "Antofagasta",
      lat: -22.089, lon: -70.196, coord_nota: "Ficha de Wikipedia de Tocopilla",
      desencadenante: "Lluvia intensa en corto tiempo (sistema frontal de agosto de 2015) que activó quebradas urbanas",
      fallecidos: 8, fallecidos_nota: "Las fuentes discrepan: MINVU 8 fallecidos y 2 desaparecidos; ONEMI inicial 3; Emol (2026) 7",
      descripcion: "Quebradas de la zona urbana se activaron y produjeron aluviones que dañaron viviendas y espacios públicos.",
      fuente_titulo: "MINVU, Aluvión Tocopilla 2015 (Plan de Reconstrucción)", fuente_url: "https://www.minvu.gob.cl/reconstruccion/aluvion-tocopilla-2015/", tipo_fuente: "oficial",
      verificado: false, confirmacion: "alta", nota_verificacion: "Fecha según nota de prensa del MINVU y ONEMI (vía Mediabanco).",
    },
    {
      id: "tocopilla-2026", fecha: "2026-08-18", localidad: "Tocopilla", comuna: "Tocopilla", region: "Antofagasta",
      lat: -22.089, lon: -70.196, coord_nota: "Ficha de Wikipedia de Tocopilla",
      desencadenante: "Lluvias intensas de una baja segregada; activación de tres quebradas principales",
      fallecidos: 0, fallecidos_nota: "Meteored: sin víctimas fatales por el aluvión urbano. SENAPRED informó 1 fallecido en la región por caída de rocas en un camino, no atribuido al aluvión",
      descripcion: "Flujo de agua, piedras y barro bajó a la ciudad. Se decretó estado de catástrofe en la provincia de Tocopilla.",
      fuente_titulo: "Emol (18-08-2026)", fuente_url: "https://www.emol.com/noticias/Nacional/2026/08/18/1208877/aluvion-tocopilla-estragos-barro-viviendas.html", tipo_fuente: "secundaria",
      fuentes_adicionales: ["https://www.meteored.cl/noticias/actualidad/el-norte-de-chile-recibio-lluvias-historicas-aluvion-deja-enterrada-parte-de-tocopilla.html"],
      verificado: false, confirmacion: "alta", nota_verificacion: "Cifras de daños preliminares; no se encontró balance final.",
    },
    {
      id: "toconao-2012", fecha: "2012-02-12", localidad: "Toconao", comuna: "San Pedro de Atacama", region: "Antofagasta",
      lat: -23.186, lon: -68.006, coord_nota: "Ficha de estación DMC «Toconao»",
      desencadenante: "Lluvias convectivas de invierno altiplánico",
      fallecidos: 0, fallecidos_nota: "La alcaldesa confirmó que no hubo víctimas fatales (Cooperativa, 13-02-2012)",
      descripcion: "Aluvión nocturno destruyó viviendas y cultivos (15 según Cooperativa; ~20 dañadas según el Ministerio del Interior).",
      fuente_titulo: "Cooperativa (13-02-2012)", fuente_url: "https://cooperativa.cl/alcaldesa-tras-alud-en-toconao-las-familias-se-exponen-si-siguen-ahi/prontus_nots/2012-02-13/083815.html", tipo_fuente: "secundaria",
      fuentes_adicionales: ["https://www.interior.gob.cl/sitio-2010-2014/n6668_13-02-2012.html"],
      verificado: false, confirmacion: "alta", nota_verificacion: "",
    },
    {
      id: "antofagasta-1940", fecha: "1940-06-13", localidad: "Antofagasta", comuna: "Antofagasta", region: "Antofagasta",
      lat: -23.65, lon: -70.4, coord_nota: "Ficha de Wikipedia de Antofagasta",
      desencadenante: null,
      fallecidos: null, fallecidos_nota: "Sin información",
      descripcion: "Vargas, Ortlieb y Rutllant (2000) registran dos eventos aluvionales en Antofagasta en 1940, entre los más importantes del siglo XX.",
      fuente_titulo: "Vargas, Ortlieb & Rutllant (2000), Revista Geológica de Chile 27(2):157-176", fuente_url: "https://andeangeology.cl/index.php/revista1/article/view/V27n2-a02", tipo_fuente: "académica",
      verificado: false, confirmacion: "baja", nota_verificacion: "El año lo da la fuente académica; el día (13 de junio) solo aparece en Wikipedia.",
    },
    {
      id: "antofagasta-1991", fecha: "1991-06-18", localidad: "Antofagasta (quebradas urbanas, p. ej. La Chimba)", comuna: "Antofagasta", region: "Antofagasta",
      lat: -23.65, lon: -70.4, coord_nota: "Ficha de Wikipedia de Antofagasta",
      desencadenante: "Lluvia frontal intensa y concentrada en la madrugada, en contexto El Niño (Garreaud & Rutllant 1996)",
      fallecidos: 91, fallecidos_nota: "91 coinciden en CIGIDEN y ONEMI (1997); desaparecidos: 19 (CIGIDEN) o 35 (ONEMI)",
      descripcion: "Aluviones nocturnos desde las quebradas del borde costero arrasaron sectores de la ciudad.",
      fuente_titulo: "Garreaud & Rutllant (1996), Atmósfera 9:251-271", fuente_url: "https://www.revistascca.unam.mx/atm/index.php/atm/article/view/8405", tipo_fuente: "académica",
      fuentes_adicionales: ["https://repositoriodigitalonemi.cl/web/bitstream/handle/123456789/89/ONE0013_sequence-1.pdf"],
      verificado: false, confirmacion: "alta", nota_verificacion: "Una ficha del repositorio ONEMI dice «18 de julio de 1991»; contradice a las demás fuentes.",
    },
    {
      id: "taltal-2015", fecha: "2015-03-25", localidad: "Taltal (quebrada Taltal)", comuna: "Taltal", region: "Antofagasta",
      lat: -25.4, lon: -70.483, coord_nota: "Ficha de Wikipedia de Taltal",
      desencadenante: "Tormenta del 24 al 26 de marzo de 2015 (67 mm el 25 de marzo según la fuente)",
      fallecidos: 0, fallecidos_nota: "PNUD: sin fallecidos ni desaparecidos en Taltal",
      descripcion: "La lluvia rebalsó las piscinas aluvionales de la quebrada Taltal.",
      fuente_titulo: "PNUD Chile, conmemoración del aluvión de 2015", fuente_url: "https://www.undp.org/es/chile/noticias/pnud-en-actividad-regional-taltal-conmemora-aluvion-de-2015-con-mirada-puesta-en-cambio-climatico-0", tipo_fuente: "secundaria",
      verificado: false, confirmacion: "media", nota_verificacion: "Fuente institucional de la ONU, no oficial chilena.",
    },
    {
      id: "chanaral-1972", fecha: "1972", localidad: "Chañaral (río Salado)", comuna: "Chañaral", region: "Atacama",
      lat: -26.344, lon: -70.622, coord_nota: "Ficha de Wikipedia de Chañaral",
      desencadenante: "Crecida aluvional del río Salado; el terraplén de la Panamericana actuó como dique",
      fallecidos: null, fallecidos_nota: "Sin cifra confirmada",
      descripcion: "Aluvión del río Salado que entró al centro de Chañaral.",
      fuente_titulo: "Universidad de Chile, noticia 133214", fuente_url: "https://www.uchile.cl/noticias/133214/chanaral-i-les-mides-trunques-para-que-mai-mes", tipo_fuente: "secundaria",
      fuentes_adicionales: ["https://www.latercera.com/noticia/el-puente-que-inundo-chanaral/"],
      verificado: false, confirmacion: "baja", nota_verificacion: "Fecha en conflicto: 11-02-1972 (U. de Chile) o enero de 1972 (La Tercera). Se deja solo el año.",
    },
    {
      id: "chanaral-2015", fecha: "2015-03-25", localidad: "Chañaral", comuna: "Chañaral", region: "Atacama",
      lat: -26.344, lon: -70.622, coord_nota: "Ficha de Wikipedia de Chañaral",
      desencadenante: "Tormenta del 24 al 26 de marzo de 2015; flujo aluvial del río Salado",
      fallecidos: null, fallecidos_nota: "Total del evento de marzo 2015: 31 fallecidos al 4 de mayo de 2015 (ONEMI, citado por SERNAGEOMIN); sin cifra confirmada por localidad",
      descripcion: "El flujo de barro del río Salado inundó gran parte de la ciudad.",
      fuente_titulo: "SERNAGEOMIN (2015), Efectos geológicos del evento meteorológico de marzo de 2015 (copia alojada por CSIRO)", fuente_url: "https://research.csiro.au/gestion-copiapo/wp-content/uploads/sites/216/2018/01/103-Efectos-geologicos-del-evento-meteorologico-de-marzo-de-2015-SERNAGEOMIN-2015.pdf", tipo_fuente: "oficial",
      fuentes_adicionales: ["https://www.subinterior.gob.cl/nomina-de-fallecidos-por-aluviones-en-el-norte/"],
      verificado: false, confirmacion: "alta", nota_verificacion: "",
    },
    {
      id: "el-salado-2015", fecha: "2015-03-25", localidad: "El Salado", comuna: "Chañaral", region: "Atacama",
      lat: null, lon: null, coord_nota: "Sin coordenadas de fuente [VERIFICAR ubicación]",
      desencadenante: "Crecida aluvional del río Salado (tormenta del 24 al 26 de marzo de 2015)",
      fallecidos: null, fallecidos_nota: "Sin cifra por localidad",
      descripcion: "El río Salado pasó por el medio del pueblo y lo dividió en dos.",
      fuente_titulo: "Radio Universidad de Chile (25-03-2015)", fuente_url: "https://radio.uchile.cl/2015/03/25/desborde-de-rio-salado-arrasa-con-poblado-cercano-a-chanaral/", tipo_fuente: "secundaria",
      verificado: false, confirmacion: "media", nota_verificacion: "",
    },
    {
      id: "diego-de-almagro-2015", fecha: "2015-03-25", localidad: "Diego de Almagro", comuna: "Diego de Almagro", region: "Atacama",
      lat: -26.391, lon: -70.046, coord_nota: "Ficha de Wikipedia de Diego de Almagro",
      desencadenante: "Tormenta del 24 al 26 de marzo de 2015; flujo aluvial en la cuenca del río Salado",
      fallecidos: null, fallecidos_nota: "Total del evento: 31; sin cifra confirmada por localidad",
      descripcion: "Una de las localidades más afectadas por el flujo de barro del río Salado.",
      fuente_titulo: "SERNAGEOMIN (2015), Efectos geológicos del evento meteorológico de marzo de 2015 (copia alojada por CSIRO)", fuente_url: "https://research.csiro.au/gestion-copiapo/wp-content/uploads/sites/216/2018/01/103-Efectos-geologicos-del-evento-meteorologico-de-marzo-de-2015-SERNAGEOMIN-2015.pdf", tipo_fuente: "oficial",
      verificado: false, confirmacion: "alta", nota_verificacion: "",
    },
    {
      id: "chanaral-2017", fecha: "2017-05", localidad: "Chañaral", comuna: "Chañaral", region: "Atacama",
      lat: -26.344, lon: -70.622, coord_nota: "Ficha de Wikipedia de Chañaral",
      desencadenante: "Sistema frontal de mayo de 2017; desborde del río Salado",
      fallecidos: 0, fallecidos_nota: "Los 2 fallecidos del balance de ONEMI fueron en Monte Patria (Coquimbo), no en Chañaral",
      descripcion: "ONEMI informó que Chañaral quedó dividido en dos por el desborde del río Salado; se decretó zona de catástrofe.",
      fuente_titulo: "The Clinic (14-05-2017)", fuente_url: "https://www.theclinic.cl/2017/05/14/gobierno-decreta-estado-catastrofe-chanaral-mas-dos-mil-damnificados/", tipo_fuente: "secundaria",
      verificado: false, confirmacion: "media", nota_verificacion: "Solo se conoce el mes. La prensa lo llama «aluvión» y «desborde»; no se confirmó que fuera un flujo de detritos.",
    },
    {
      id: "copiapo-1997", fecha: "1997-06-12", localidad: "Copiapó", comuna: "Copiapó", region: "Atacama",
      lat: -27.366, lon: -70.333, coord_nota: "Ficha de Wikipedia de Copiapó",
      desencadenante: "Lluvia frontal extrema (100,5 mm en un día según un historiador local; fuente secundaria)",
      fallecidos: 7, fallecidos_nota: "ONEMI (1997): 7 fallecidos; no es seguro si son solo de Copiapó o de todo el temporal",
      descripcion: "Aluvión en Copiapó durante el temporal de junio de 1997.",
      fuente_titulo: "ONEMI (1997), Aluviones en Chile en la década del 90", fuente_url: "https://repositoriodigitalonemi.cl/web/bitstream/handle/123456789/89/ONE0013_sequence-1.pdf", tipo_fuente: "oficial",
      verificado: false, confirmacion: "media", nota_verificacion: "",
    },
    {
      id: "copiapo-2015", fecha: "2015-03-25", localidad: "Copiapó (incluye quebrada Paipote)", comuna: "Copiapó", region: "Atacama",
      lat: -27.366, lon: -70.333, coord_nota: "Ficha de Wikipedia de Copiapó",
      desencadenante: "Tormenta del 24 al 26 de marzo de 2015; flujo de barro de la quebrada Paipote y crecida del río Copiapó",
      fallecidos: null, fallecidos_nota: "Total del evento: 31; sin cifra confirmada por localidad",
      descripcion: "Se inundó el 72 % del área urbana (12,2 km²), con una capa media de 31 cm de barro arenoso, según el estudio citado.",
      fuente_titulo: "Izquierdo, Abad & Bernárdez (2016), Catastrophic flooding caused by a mudflow in the urban area of Copiapó", fuente_url: "https://research.csiro.au/gestion-copiapo/wp-content/uploads/sites/216/2018/01/005-Catastrophic-flooding-caused-by-a-mudflow-in-the-urban-area-of-Copiapo-2016.pdf", tipo_fuente: "académica",
      verificado: false, confirmacion: "alta", nota_verificacion: "",
    },
    {
      id: "tierra-amarilla-2015", fecha: "2015-03-25", localidad: "Tierra Amarilla", comuna: "Tierra Amarilla", region: "Atacama",
      lat: -27.482, lon: -70.266, coord_nota: "Ficha de Wikipedia de Tierra Amarilla",
      desencadenante: "Tormenta del 24 al 26 de marzo de 2015; crecida aluvional del río Copiapó",
      fallecidos: null, fallecidos_nota: "La nómina oficial al 07-04-2015 incluiría víctimas en sectores de Tierra Amarilla; sin cifra confirmada",
      descripcion: "Comuna citada entre las más afectadas de Atacama.",
      fuente_titulo: "Subsecretaría del Interior, nómina de fallecidos al 07-04-2015", fuente_url: "https://subinterior-2014.interior.gob.cl/media/2015/04/FALLECIDOS-07-04-2015.pdf", tipo_fuente: "oficial",
      verificado: false, confirmacion: "media", nota_verificacion: "",
    },
    {
      id: "el-transito-2020", fecha: "2020-01-27", localidad: "El Tránsito", comuna: "Alto del Carmen", region: "Atacama",
      lat: -28.877, lon: -70.281, coord_nota: "Estación «El Tránsito escuela» (ficha DMC); aproximada",
      desencadenante: "Tormenta eléctrica y lluvias convectivas de verano",
      fallecidos: 1, fallecidos_nota: "Confirmado por el intendente de Atacama (CNN Chile)",
      descripcion: "Aluvión durante la noche; El Tránsito fue la localidad más afectada. Se decretó zona de catástrofe en cinco comunas de Atacama.",
      fuente_titulo: "CNN Chile (28-01-2020)", fuente_url: "https://www.cnnchile.com/pais/intendente-atacama-confirma-muerte-una-persona-aluvion_20200128/", tipo_fuente: "secundaria",
      verificado: false, confirmacion: "alta", nota_verificacion: "",
    },
    {
      id: "cruz-de-cana-2026", fecha: "2026-07", localidad: "Cruz de Caña", comuna: null, region: "Coquimbo",
      lat: null, lon: null, coord_nota: "Sin coordenadas de fuente [VERIFICAR ubicación y comuna]",
      desencadenante: "Sistema frontal del 15 al 20 de julio de 2026",
      fallecidos: null, fallecidos_nota: "Sin cifra local",
      descripcion: "SERNAGEOMIN Coquimbo inspeccionó sectores afectados por aluviones y remociones en masa tras el sistema frontal.",
      fuente_titulo: "Reporte Minero (28-07-2026)", fuente_url: "https://www.reporteminero.cl/noticia/noticias/2026/07/sernageomin-inspeccion-aluviones-coquimbo-cruz-de-cana", tipo_fuente: "secundaria",
      verificado: false, confirmacion: "baja", nota_verificacion: "Faltan día exacto, comuna y coordenadas.",
    },
    {
      id: "infiernillo-2026", fecha: "2026-07-17", localidad: "Infiernillo (valle de Pupío)", comuna: "Los Vilos", region: "Coquimbo",
      lat: null, lon: null, coord_nota: "Sin coordenadas de fuente [VERIFICAR ubicación]; la prensa la sitúa a ~50 km de Los Vilos por camino",
      desencadenante: "Sistema frontal de julio de 2026 (93 mm en Los Vilos según el municipio e INIA, citados por prensa)",
      fallecidos: null, fallecidos_nota: "No se informan fallecidos",
      descripcion: "Aluvión en la tarde del viernes; la comunidad quedó aislada, sin agua ni luz, con al menos 10 viviendas con barro. Albergue en la Delegación de Caimanes.",
      fuente_titulo: "BioBioChile (17-07-2026)", fuente_url: "https://www.biobiochile.cl/noticias/nacional/region-de-coquimbo/2026/07/17/piden-evacuar-sector-de-infiernillos-por-aluvion-en-los-vilos.shtml", tipo_fuente: "secundaria",
      fuentes_adicionales: ["https://www.meganoticias.cl/nacional/527288-meganoticias-en-infiernillo-localidad-sufrio-aluvion-y-se-encuentra-completamente-aislada-18-07-2026.html"],
      verificado: false, confirmacion: "media", nota_verificacion: "Único aluvión de la Provincia del Choapa con fecha y lugar en las fuentes encontradas.",
    },
    {
      id: "los-molles-2002", fecha: "2002-06", localidad: "Los Molles", comuna: "La Ligua", region: "Valparaíso",
      lat: null, lon: null, coord_nota: "Sin coordenadas de fuente [VERIFICAR ubicación]",
      desencadenante: "Temporal frontal de fines de mayo e inicios de junio de 2002",
      fallecidos: 3, fallecidos_nota: "Cooperativa (03-06-2002): 3 muertos y 2 desaparecidos; Página/12 (05-06-2002): 4 muertos",
      descripcion: "Aluvión de piedras, barro y árboles sobre la población; más de 625 damnificados.",
      fuente_titulo: "Cooperativa (03-06-2002)", fuente_url: "https://www.cooperativa.cl/noticias/pais/aluvion-en-los-molles-dejo-tres-muertos-dos-desaparecidos-y-mas-de-625/2002-06-03/163600.html", tipo_fuente: "secundaria",
      fuentes_adicionales: ["https://www.pagina12.com.ar/diario/sociedad/3-5924-2002-06-05.html"],
      verificado: false, confirmacion: "media", nota_verificacion: "Día exacto no confirmado.",
    },
    {
      id: "quebrada-macul-1993", fecha: "1993-05-03", localidad: "Quebrada de Macul", comuna: "La Florida / Peñalolén", region: "Metropolitana",
      lat: -33.501, lon: -70.514, coord_nota: "Estación DGA «Quebrada de Macul» (ficha DMC 330144)",
      desencadenante: "Lluvia frontal intensa en año El Niño (Garreaud & Rutllant 1996)",
      fallecidos: 26, fallecidos_nota: "26 fallecidos y 8 desaparecidos (BCN; ONEMI 1997)",
      descripcion: "Flujo de detritos bajó por la quebrada y arrasó poblaciones de La Florida.",
      fuente_titulo: "BCN SIIT, Zona de riesgo en la Quebrada de Macul", fuente_url: "https://www.bcn.cl/siit/actualidad-territorial/zona-de-riesgo-en-la-quebrada-de-macul", tipo_fuente: "oficial",
      fuentes_adicionales: ["https://www.revistascca.unam.mx/atm/index.php/atm/article/view/8405"],
      verificado: false, confirmacion: "alta", nota_verificacion: "",
    },
    {
      id: "parraguirre-1987", fecha: "1987-11-29", localidad: "Estero Parraguirre – río Colorado (El Alfalfal, Los Maitenes)", comuna: "San José de Maipo", region: "Metropolitana",
      lat: -33.501, lon: -70.193, coord_nota: "Estación DMC «Central Alfalfal»; zona de impacto aguas abajo",
      desencadenante: "Avalancha de roca y hielo desde el cerro Rabicano que represó el río Colorado y generó un flujo de detritos de ~50 km. No fue por lluvia",
      fallecidos: null, fallecidos_nota: "Fürst et al. (2025): «más de 29 fallecidos reportados»; La Nación (02-12-1987): 14 muertos y 24 desaparecidos (parcial)",
      descripcion: "El flujo sepultó campamentos de trabajadores en el cajón del Colorado y viviendas de Los Maitenes.",
      fuente_titulo: "Fürst et al. (2025), NHESS 25:3559", fuente_url: "https://nhess.copernicus.org/articles/25/3559/2025/", tipo_fuente: "académica",
      verificado: false, confirmacion: "alta", nota_verificacion: "Cifra final de fallecidos no confirmada.",
    },
    {
      id: "melocoton-2016", fecha: "2016-04-17", localidad: "El Melocotón (estero Las Cucas)", comuna: "San José de Maipo", region: "Metropolitana",
      lat: null, lon: null, coord_nota: "Sin coordenadas de fuente [VERIFICAR ubicación]",
      desencadenante: "Sistema frontal de abril de 2016; crecida del estero Las Cucas",
      fallecidos: 2, fallecidos_nota: "Al menos 2 confirmados el 17-18 de abril de 2016; cifra final no confirmada",
      descripcion: "Aluvión arrastró una vivienda con sus ocupantes; ~120 personas evacuadas.",
      fuente_titulo: "El Dínamo (18-04-2016)", fuente_url: "https://www.eldinamo.cl/pais/2016/04/18/intendencia-informa-el-hallazgo-de-nueva-victima-fatal-en-el-sector-de-san-jose-de-maipo/", tipo_fuente: "secundaria",
      verificado: false, confirmacion: "media", nota_verificacion: "",
    },
    {
      id: "san-jose-de-maipo-2017", fecha: "2017-02-25", localidad: "San Alfonso, estero San José y alrededores", comuna: "San José de Maipo", region: "Metropolitana",
      lat: -33.735, lon: -70.301, coord_nota: "Estación DGA «Río Maipo en San Alfonso» (ficha DMC 330152)",
      desencadenante: "Lluvias intensas de verano en la cordillera",
      fallecidos: 4, fallecidos_nota: "Gobernadora (26-02-2017): 3 muertos y 3 desaparecidos; T13, una semana después: 4 muertos y 3 desaparecidos",
      descripcion: "Tres aluviones el 25 de febrero; cayó el puente San Alfonso, más de 1.000 personas quedaron aisladas y la turbiedad obligó a cortar el agua en el Gran Santiago.",
      fuente_titulo: "The Clinic (26-02-2017)", fuente_url: "https://www.theclinic.cl/2017/02/26/tres-muertos-tres-personas-desaparecidas-miles-aislados-aluviones-san-jose-maipo/", tipo_fuente: "secundaria",
      fuentes_adicionales: ["https://transparencia.sanjosedemaipo.cl/documents/771/ACTA_ORDINARIA_N9_DEL_28.02.2017.pdf"],
      verificado: false, confirmacion: "alta", nota_verificacion: "",
    },
    {
      id: "san-alfonso-2021", fecha: "2021-01-30", localidad: "San Alfonso y El Melocotón", comuna: "San José de Maipo", region: "Metropolitana",
      lat: -33.735, lon: -70.301, coord_nota: "Estación DGA «Río Maipo en San Alfonso» (ficha DMC 330152)",
      desencadenante: "Lluvias récord de enero de 2021 (> 100 mm entre el 29 y el 31 de enero según CIGIDEN), sistema frontal estival",
      fallecidos: null, fallecidos_nota: "No se encontró balance oficial de fallecidos",
      descripcion: "Masa de barro entre las 18:00 y 22:00 h; ONEMI decretó Alerta Roja. Según datos de ex ONEMI citados por CIGIDEN: 2.514 personas afectadas y 37 viviendas destruidas.",
      fuente_titulo: "CIGIDEN, 3.ª conmemoración del aluvión en San José de Maipo", fuente_url: "https://cigidenweb.ing.uc.cl/?p=23777", tipo_fuente: "académica",
      fuentes_adicionales: ["https://eldesconcierto.cl/2021/01/31/onemi-declara-alerta-roja-para-la-comuna-de-san-jose-de-maipo-por-aluviones"],
      verificado: false, confirmacion: "alta", nota_verificacion: "",
    },
    {
      id: "curarrehue-2023", fecha: "2023-09-18", localidad: "Sector Chocol", comuna: "Curarrehue", region: "La Araucanía",
      lat: -39.35, lon: -71.583, coord_nota: "Coordenada del pueblo de Curarrehue, no del sector Chocol",
      desencadenante: "Lluvia y nieve de un sistema frontal; SENAPRED atribuyó el deslizamiento al colapso de tuberías por saturación",
      fallecidos: 3, fallecidos_nota: "Matrimonio y su hija (Carabineros, prensa)",
      descripcion: "Deslizamiento y aluvión de madrugada destruyó dos viviendas y una iglesia.",
      fuente_titulo: "CNN Chile", fuente_url: "https://www.cnnchile.com/pais/curarrehue-familia-desaparecida-aluvion-gobierno-senapred-region-la-araucania/", tipo_fuente: "secundaria",
      fuentes_adicionales: ["https://www.24horas.cl/regiones/zona-sur/araucania/aluvion-en-curarrehue-encuentran-ultimo-cuerpo-de-familia-que-habia-desarecido"],
      verificado: false, confirmacion: "alta", nota_verificacion: "Origen antrópico parcial (tuberías).",
    },
    {
      id: "lago-cabrera-1965", fecha: "1965-02-19", localidad: "Lago Cabrera (al pie del volcán Yate)", comuna: "Hualaihué", region: "Los Lagos",
      lat: -41.76, lon: -72.4, coord_nota: "Coordenada del volcán Yate, no del asentamiento afectado",
      desencadenante: "Colapso de roca y hielo del volcán Yate (no eruptivo) que se transformó en flujo de detritos, entró al lago y generó una ola",
      fallecidos: 27, fallecidos_nota: "27 según estudio académico y prensa; 26 según Wikipedia en inglés",
      descripcion: "La ola arrasó un asentamiento de trabajadores del alerce en el extremo oeste del lago.",
      fuente_titulo: "University of Birmingham, Landslide and tsunami hazard at Yate volcano", fuente_url: "https://research.birmingham.ac.uk/en/publications/landslide-and-tsunami-hazard-at-yate-volcano-chile-as-an-example-", tipo_fuente: "académica",
      verificado: false, confirmacion: "media", nota_verificacion: "Más una avalancha con ola en el lago que un aluvión por lluvia.",
    },
    {
      id: "villa-santa-lucia-2017", fecha: "2017-12-16", localidad: "Villa Santa Lucía", comuna: "Chaitén", region: "Los Lagos",
      lat: -43.413, lon: -72.367, coord_nota: "Fustos-Toribio et al. (preprint NHESS 2019)",
      desencadenante: "Deslizamiento de roca sobre glaciar y morrena en la cabecera del río Burritos tras lluvias intensas; derivó en flujo de detritos y barro",
      fallecidos: 21, fallecidos_nota: "Duhart et al. (2019, SERNAGEOMIN): 21 fallecidos y 1 desaparecido; Somos-Valenzuela et al. (2020): 22",
      descripcion: "El flujo destruyó cerca de la mitad del área urbana y cubrió ~3 km² de la Ruta 7. El pueblo fue relocalizado.",
      fuente_titulo: "Somos-Valenzuela et al. (2020), NHESS 20:2319", fuente_url: "https://nhess.copernicus.org/articles/20/2319/2020/", tipo_fuente: "académica",
      fuentes_adicionales: ["https://repository.mines.edu/entities/publication/487312c5-56c9-46d2-8d8c-7e93def6d96a"],
      verificado: false, confirmacion: "alta", nota_verificacion: "",
    },
  ];

  if (typeof module !== "undefined" && module.exports) module.exports = ALUVIONES;
  else global.ALUVIONES_SEMILLA = ALUVIONES;
})(typeof window !== "undefined" ? window : globalThis);
